name: Lighthouse Badger (disabled)

on:
  workflow_dispatch:

jobs:
  do_nothing:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo "This workflow is disabled and does nothing."
